In [1]:
import math
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
from scipy.stats import chi2_contingency
from IPython.display import display

In [2]:
# Create a contingency table
# In the two-dimensional case, the table is often described as an “R x C table”.
observed = np.array([[10, 20, 30, 40, 50], [51, 38, 32, 18, 11]])

In [3]:
# Perform the chi-square test of independence
chi2, p, dof, expected = chi2_contingency(observed)

# Print the results
print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 66.48735389047941
p-value: 1.250359608337329e-13
Degrees of freedom: 4
Expected frequencies:
 [[30.5 29.  31.  29.  30.5]
 [30.5 29.  31.  29.  30.5]]


In [4]:
# Create a contingency table
# In the two-dimensional case, the table is often described as an “R x C table”.
observed = np.array([[10, 20, 30, 40, 50], [9, 21, 37, 45, 47]])

In [5]:
# Perform the chi-square test of independence
chi2, p, dof, expected = chi2_contingency(observed)

# Print the results
print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 0.9339226167894914
p-value: 0.919644419468446
Degrees of freedom: 4
Expected frequencies:
 [[ 9.22330097 19.90291262 32.52427184 41.26213592 47.08737864]
 [ 9.77669903 21.09708738 34.47572816 43.73786408 49.91262136]]


In [6]:
# no of hours a student studies
# in a week vs expected no of hours
observed_data = [10, 20, 30, 40, 50]
expected_data = [51, 38, 32, 18, 11]

In [7]:
# Chi-Square Goodness of Fit Test
chi_square_test_statistic, p_value = stats.chisquare(
    observed_data, expected_data)
  
# chi square test statistic and p value
print('Chi-square statistic is: ' +
      str(chi_square_test_statistic))
print('p-value: ' + str(p_value))

Chi-square statistic is: 206.77371626481533
p-value: 1.313118252244011e-43


In [8]:
# the degrees of freedom, df, formula is
nrows = 2
ncols = len(observed_data)
df = (nrows - 1) * (ncols - 1)
print('Degrees of freedom: ' + str(df))

# significance level
alpha = 0.05

# find Chi-Square critical value
crit = stats.chi2.ppf(1-alpha, df = df)
print('Critical value: ' + str(crit))

crit = stats.chi2.ppf(q = 1-alpha, # Find the critical value for 95% confidence*
                      df = df)   # Df = number of variable categories - 1

print('Critical value: ' + str(crit))

p_value = 1 - stats.chi2.cdf(x=chi_square_test_statistic,  # Find the p-value
                             df = df) # Df = number of variable categories - 1

print('p-value: ' + str(p_value))

Degrees of freedom: 4
Critical value: 9.487729036781154
Critical value: 9.487729036781154
p-value: 0.0
